version: '3.7'

services:
  mongodb:
    image: mongo:5.0.0
    container_name: mongodb
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - "27017:27017"
    environment:
      - MONGO_URL=mongodb://mongo:27017/url-shortener
  redis:
    image: redis:6.0.5
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  node_modules:
  esdata:
    driver: local
